# Generated by Django 2.2.4 on 2020-04-19 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200417_1929'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModelName',
        ),
    ]
